Fix ssl redirect
deliverycenter/hey_doctor pull request #9
Opened 2021-08-26 02:19 UTC by the-harry

**What is the content type?**

  - Bugfix

**Why is this change necessary?**

  - In some cases, behind an ALB with ssl the application may redirect this to port 443 when `force_ssl` is set to true. This makes the main application unhealthy since the response code is not 200 - ok.

**How does it address the issue?**

  - It follow internal redirects if the response is a `Net::HTTPRedirection`, otherwise responds normally.
  - if it redirects more than 3 times it stops.

**What side effects does this change have?**

  - none

**Does this change include database migrations? (If yes please list)**

   - nops

2021-09-08 18:40 UTC, jairojj approved these changes

2021-09-09 11:21 UTC, danielmciotti commented on app/services/hey_doctor/check_application_health_service.rb
> +    DEFAULT_PORT = ENV['RAILS_PORT'] || ENV['PORT']
We suppose this is set by a K8s configMap or GCP Secrets, right? If so, it might be a good idea to keep an eye on [Puma Ports](https://github.com/puma/puma/blob/319f84db13ee59f7b24885cec686d5c714998a4c/lib/puma/dsl.rb#L258) as well

2021-09-09 11:21 UTC, danielmciotti commented on app/services/hey_doctor/check_application_health_service.rb
> +        return app_http_code(location[1], 443) unless location.nil?
what if a infinite loop occurs?

2021-09-09 13:07 UTC, the-harry commented on app/services/hey_doctor/check_application_health_service.rb
> +    DEFAULT_PORT = ENV['RAILS_PORT'] || ENV['PORT']
Yeah, for sure! This in fact is a technical debit huaehauehae, I tried to access the application port when it was first developed but I couln't make it work, I think I did it other way, but it always returned 3000 to me even though the application is running in other port.
But I'll take a look at this, it'd be great to remove this config!

2021-09-09 13:17 UTC, the-harry commented on app/services/hey_doctor/check_application_health_service.rb
> +        return app_http_code(location[1], 443) unless location.nil?
Good point! I'll add a limit_counter to it!

2021-09-09 15:38 UTC, devnetomartins approved these changes

2021-09-14 20:03 UTC, lucas-sandeville-dc requested changes
this PR will merge with the `master` branch. Shouldn't it be merging with the `develop` branch?

2021-09-14 21:22 UTC, the-harry commented
> this PR will merge with the `master` branch. Shouldn't it be merging with the `develop` branch?

no, it shouldn't. Ain't no develop branch here, it's a small project there's no need to other branch.

2021-09-14 22:02 UTC, lucas-sandeville-dc approved these changes

2021-09-16 13:56 UTC, gahorstmann approved these changes

2021-09-24 14:35 UTC, the-harry commented on app/services/hey_doctor/check_application_health_service.rb
> +    DEFAULT_PORT = ENV['RAILS_PORT'] || ENV['PORT']
@danielmciotti I'm gonna resolve this for now, but I've opened a issue to deal with it in #11

2021-09-24 14:50 UTC, the-harry commented on app/services/hey_doctor/check_application_health_service.rb
> +        return app_http_code(location[1], 443) unless location.nil?
Done, @danielmciotti ! 🚀

2021-09-24 15:05 UTC, jairojj approved these changes

2021-09-24 15:06 UTC, Hoffmeisters approved these changes

2021-09-24 15:30 UTC, merged